name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test

        # Put your action repo here
        uses: jacobtomlinson/go-container-action@master
